export const START_TIME = 9
export const END_TIME = 17
export const INCREMENT_MINS = 15

export const COST_MATRIX_CELL_WIDTH_PX = 100
export const COST_MATRIX_HEADER_CELL_HEIGHT_PX = 50
export const COST_MATRIX_CONTENT_CELL_HEIGHT_PX = 100

export const SCHEDULE_CELL_WIDTH_PX = 100
export const SCHEDULE_HEADER_CELL_HEIGHT_PX = 50
export const SCHEDULE_CONTENT_CELL_HEIGHT_PX = 100